// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNbamCAYuFbuoyMZFTKPatjp_teuR_oM',
    appId: '1:449872052003:web:7ab3040af3f04aa46d5696',
    messagingSenderId: '449872052003',
    projectId: 'restflow-b1298',
    authDomain: 'restflow-b1298.firebaseapp.com',
    storageBucket: 'restflow-b1298.firebasestorage.app',
    measurementId: 'G-DZ4LXKGDE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIPk4mM-GdrLdR0WyK8JwhPqfcqNBvOA',
    appId: '1:449872052003:android:7162fe29e724bed26d5696',
    messagingSenderId: '449872052003',
    projectId: 'restflow-b1298',
    storageBucket: 'restflow-b1298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbe2Mj2UPRbVYtz2ek2qMHIrNVQhSsRSY',
    appId: '1:449872052003:ios:3bc8a6faf9628f2e6d5696',
    messagingSenderId: '449872052003',
    projectId: 'restflow-b1298',
    storageBucket: 'restflow-b1298.firebasestorage.app',
    iosBundleId: 'com.example.restFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbe2Mj2UPRbVYtz2ek2qMHIrNVQhSsRSY',
    appId: '1:449872052003:ios:3bc8a6faf9628f2e6d5696',
    messagingSenderId: '449872052003',
    projectId: 'restflow-b1298',
    storageBucket: 'restflow-b1298.firebasestorage.app',
    iosBundleId: 'com.example.restFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARNbamCAYuFbuoyMZFTKPatjp_teuR_oM',
    appId: '1:449872052003:web:2b97e0b259f712fa6d5696',
    messagingSenderId: '449872052003',
    projectId: 'restflow-b1298',
    authDomain: 'restflow-b1298.firebaseapp.com',
    storageBucket: 'restflow-b1298.firebasestorage.app',
    measurementId: 'G-SW6HJSRVZP',
  );
}
